import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import logo from "./../assets/images/logo.png";
import { FooterData, navLinks, social } from "@/data";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
const Podcast = localFont({
  src: [
    {
      path: "./../assets/fonts/Podcast.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--podcast",
});

const openSans = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "tours to Touscany!",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    height: "device-height",
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body>
        <main
          className={`relative ${openSans.className} ${Podcast.variable} antialiased`}
        >
          <Navbar logo={logo} links={navLinks} />
          {children}
          <Footer image={logo} footerData={FooterData} socialLink={social} />
        </main>
      </body>
    </html>
  );
}
